<?xml version="1.0"?>
<package format="3">
  <name>neugrasp_bringup</name>
  <version>0.0.1</version>
  <description>Application launch, static scene frames and RViz configuration for Neugrasp.</description>
  <maintainer email="maintainer@example.com">myarm_sdk maintainers</maintainer>
  <license>All rights reserved</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>myarm_bringup</exec_depend>
  <exec_depend>myarm_cartesian_trajectory</exec_depend>
  <exec_depend>myarm_description</exec_depend>
  <exec_depend>myarm_neugrasp</exec_depend>
  <exec_depend>myarm_rviz2</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export><build_type>ament_python</build_type></export>
</package>
